bw2_api.settings:
  type: config_object
  label: 'bw2 API settings'
  mapping:
    base_url:
      type: string
      label: 'Base url'
    portalguid:
      type: string
      label: 'Portal UID'
    objectguid_get:
      type: string
      label: 'Object UID for the GET Requests'
    objectguid_post:
      type: string
      label: 'Object UID for the POST / PATCH Requests'
    current_item_version:
      type: string
      label: 'Latest version of the bw2 API'
