bw2_api.settings:
  type: config_object
  label: 'bw2 API settings'
  mapping:
    base_url:
      type: string
      label: 'Base url'
    # newsletter:
    #   type: string
    #   label: 'Newsletter'
    portaluid:
      type: string
      label: 'Portal UID'
    objectuid_get:
      type: string
      label: 'Object UID for the GET Requests'
    objectuid_post:
      type: string
      label: 'Object UID for the POST / PATCH Requests'
